---
abstract: 'Helpers for keeping a set of related .po files in sync'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-POFileManager
requires:
  ExtUtils::MakeMaker: 6.11
  File::Temp: 0.19
  List::MoreUtils: 0
  Locale::PO: 0
  Moose: 0.90
  MooseX::Types::Path::Class: 0
  Scalar::Util: 0
version: 0.02
